# Generated by Django 4.2.3 on 2023-08-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.BooleanField(default=False)),
                ('transfer', models.BooleanField(default=False)),
                ('resettlement', models.BooleanField(default=False)),
            ],
        ),
    ]
