# Generated by Django 4.2.3 on 2023-07-30 00:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('otchestvo', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('vkurl', models.URLField(unique=True)),
                ('tgurl', models.CharField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
    ]
