# Generated by Django 4.2.3 on 2023-08-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='otchestvo',
            new_name='patronymic',
        ),
    ]
