# Generated by Django 4.2.3 on 2023-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_rename_otchestvo_transfer_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='patronymic',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
