# Generated by Django 4.2.3 on 2023-09-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_alter_transfer_tgurl_alter_transfer_vkurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer',
            field=models.CharField(choices=[('Да, от Одинцово и обратно', 'Да, от Одинцово и обратно'), ('Да, от Парка Победы и обратно', 'Да, от Парка Победы и обратно')], default='Да, от Одинцово и обратно', max_length=254),
            preserve_default=False,
        ),
    ]
