# Generated by Django 4.2.3 on 2023-09-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_transfer_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='departure_time',
            field=models.CharField(choices=[('15:15', '15:15'), ('15:35', '15:35'), ('15:55', '15:55'), ('17:35', '17:35'), ('16:45', '16:45'), ('17:25', '17:25'), ('17:45', '17:45'), ('18:25', '18:25'), ('18:45', '18:45'), ('19:25', '19:25')], default=None, max_length=30),
        ),
    ]
