# Generated by Django 4.2.3 on 2023-07-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('otchestvo', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('vkurl', models.URLField(unique=True)),
                ('tgurl', models.CharField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=254)),
                ('birth_date', models.DateField(max_length=254)),
                ('sex', models.CharField(max_length=50)),
                ('univer', models.CharField(max_length=254)),
                ('faculty', models.CharField(max_length=254)),
                ('program', models.CharField(max_length=254)),
                ('year', models.IntegerField()),
                ('group', models.CharField(max_length=254)),
                ('transfer', models.CharField(max_length=254)),
                ('health', models.CharField(max_length=254)),
            ],
        ),
    ]
