# Generated by Django 4.2.3 on 2023-07-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=50),
        ),
    ]
