# Generated by Django 4.2.3 on 2023-07-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_registration_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=20),
        ),
    ]
