# Generated by Django 4.2.3 on 2023-07-31 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_registration_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
