# Generated by Django 4.2.3 on 2023-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_alter_registration_health_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='patronymic',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
