# Generated by Django 4.2.3 on 2023-08-28 01:43

import PosvyatSite.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100)),
                ('vkurl', models.CharField(max_length=255, unique=True, validators=[PosvyatSite.validators.validate_vk_url])),
                ('tgurl', models.CharField(max_length=254, unique=True, validators=[PosvyatSite.validators.validate_tg_link])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('program', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('people_custom', models.JSONField(default=list)),
            ],
        ),
    ]
