# Generated by Django 4.2.3 on 2023-07-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('otchestvo', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Resettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('otchestvo', models.CharField(max_length=254)),
                ('vkurl', models.URLField(unique=True)),
                ('tgurl', models.CharField(max_length=254, unique=True)),
                ('program', models.CharField(max_length=254)),
                ('group', models.CharField(max_length=254)),
                ('year', models.IntegerField()),
                ('people', models.ManyToManyField(to='resettlement.person')),
            ],
        ),
    ]
