# Generated by Django 4.2.3 on 2023-09-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resettlement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettlement',
            name='people_custom',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
