# Generated by Django 4.2.3 on 2023-07-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resettlement', '0002_rename_name_person_fio_remove_person_otchestvo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resettlement',
            old_name='people',
            new_name='people_custom',
        ),
    ]
