# Generated by Django 4.2.3 on 2023-07-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resettlement', '0003_rename_people_resettlement_people_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resettlement',
            name='people_custom',
        ),
        migrations.AlterField(
            model_name='resettlement',
            name='group',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resettlement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resettlement',
            name='otchestvo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resettlement',
            name='program',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resettlement',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resettlement',
            name='tgurl',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resettlement',
            name='vkurl',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
