# Generated by Django 4.2.3 on 2023-07-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resettlement', '0004_remove_resettlement_people_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resettlement',
            name='people_custom',
            field=models.JSONField(default=list),
        ),
    ]
