# Generated by Django 4.2.3 on 2023-08-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resettlement', '0008_alter_resettlement_people_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettlement',
            name='people_custom',
            field=models.JSONField(default=list),
        ),
    ]
