# Generated by Django 4.2.3 on 2023-08-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resettlement', '0010_alter_resettlement_people_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resettlement',
            old_name='otchestvo',
            new_name='patronymic',
        ),
    ]
