# Generated by Django 4.2.3 on 2023-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resettlement', '0011_rename_otchestvo_resettlement_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettlement',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
